# api/auth.py
from fastapi import APIRouter, Depends, HTTPException, Request, Response
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from core.db import get_db_session
from core.models import User
from core.security import (
    IS_PRODUCTION,
    hash_password,
    verify_password,
    create_access_token,
    create_refresh_token,
    decode_token,
    REFRESH_TOKEN_EXPIRE_DAYS,
)
from schema.auth import RegisterRequest, LoginRequest, UserResponse, AccessTokenResponse

router = APIRouter(prefix="/api/auth", tags=["Auth"])

REFRESH_COOKIE_NAME = "refresh_token"


@router.post("/register", response_model=UserResponse)
async def register(payload: RegisterRequest, session: AsyncSession = Depends(get_db_session)):
    # Check for an existing user with this email BEFORE inserting — a
    # cleaner error than letting the database's unique constraint throw
    # a raw IntegrityError up to the client.
    existing = await session.execute(select(User).where(User.email == payload.email))
    if existing.scalar_one_or_none() is not None:
        raise HTTPException(status_code=409, detail="Email already registered")

    user = User(email=payload.email,
                hashed_password=hash_password(payload.password))
    session.add(user)
    await session.commit()
    await session.refresh(user)  # populates user.id, generated by the DB

    return UserResponse(id=user.id, email=user.email)


@router.post("/login", response_model=AccessTokenResponse)
async def login(payload: LoginRequest, response: Response, session: AsyncSession = Depends(get_db_session)):
    result = await session.execute(select(User).where(User.email == payload.email))
    user = result.scalar_one_or_none()

    # Deliberately the SAME error for "no such user" and "wrong password"
    # — telling an attacker WHICH one was wrong (user enumeration) is a
    # real, avoidable information leak.
    if user is None or not verify_password(payload.password, user.hashed_password):
        raise HTTPException(
            status_code=401, detail="Invalid email or password")

    access_token = create_access_token(user.id)
    refresh_token = create_refresh_token(user.id)

    # httpOnly=True: JavaScript can never read this cookie (XSS-safe).
    # secure=True: only sent over HTTPS — in local dev over plain http
    # this will silently prevent the cookie being set, so this needs
    # toggling off (or handled via an env var) for local testing.
    # samesite="lax": reasonable default CSRF mitigation for same-site
    # navigation while still allowing normal top-level requests.
    response.set_cookie(
        key=REFRESH_COOKIE_NAME,
        value=refresh_token,
        httponly=True,
        secure=IS_PRODUCTION,  # only require HTTPS once actually deployed
        samesite="lax",
        max_age=REFRESH_TOKEN_EXPIRE_DAYS * 24 * 60 * 60,
        path="/api/auth",
    )

    return AccessTokenResponse(access_token=access_token)


@router.post("/refresh", response_model=AccessTokenResponse)
async def refresh(request: Request):
    refresh_token = request.cookies.get(REFRESH_COOKIE_NAME)
    if not refresh_token:
        raise HTTPException(status_code=401, detail="Missing refresh token")

    user_id = decode_token(refresh_token, expected_type="refresh")
    new_access_token = create_access_token(user_id)

    return AccessTokenResponse(access_token=new_access_token)


@router.post("/logout")
async def logout(response: Response):
    # JWTs can't be individually invalidated server-side without extra
    # infrastructure (a denylist store) — "logout" here just means
    # deleting the refresh cookie, so no new access tokens can be
    # obtained. Any currently-held access token remains technically
    # valid until it naturally expires (15 min) — an accepted tradeoff
    # of pure stateless JWT, not a bug.
    response.delete_cookie(key=REFRESH_COOKIE_NAME, path="/api/auth")
    return {"detail": "Logged out"}
